spring.application.name=reto_examen

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-dawn-fog-a4qdgt10-pooler.us-east-1.aws.neon.tech/db_reto?sslmode=require
spring.datasource.username=db_reto_owner
spring.datasource.password=npg_B0MlSxgdkYH6

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Loggin (para ver errores detallado)
logging.level.org.springframework=DEBUG

#Spring security (credenciales basicas)
spring.security.user.name=admin
spring.security.user.password=admin

# Configuración del pool de conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000